apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: webapp
rules:
  - apiGroups: 
         - ""
         - apps
         - autoscaling
         - batch
         - extensions
         - policy
         - rbac.authorization.k8s.io
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
      - persistentvolumeclaims
      - ingress
      - jobs
      - namespaces
      - nodes
      - persistentvolumes
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
