apiVersion: v1
kind: Service
metadata:
  name: java-maven-apps-svc
  namespace: webapp
  labels:
    app: java-maven-apps
spec:
  type: LoadBalancer
  selector:
    app: java-maven-apps
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
